FROM alpine:edge

RUN apk --no-cache --update add \
  curl \
	tar

	&& curl -L -o caddy.tar.gz https://github.com/mholt/caddy/releases/download/v0.10.0/caddy_v0.10.0_linux_amd64.tar.gz \
	&& tar xvf caddy.tar.gz \

